### ISSUE TITLE
multiple properties on a nested object does not work

### ISSUE THREAD

**Issue by papayaah** [abraham-serafino/react-data-binding#1] opened 2017-08-05 23:28 UTC
if you have a state that looks like this:

```
this.state = { . 
  billing: {
    firstName: 'Alice',
    lastName: 'Wonderland'
  }
}
```

and use it like this: 
```
<input className="it1" type="text" {...model('billing.firstName')} />
<input className="it1" type="text" {...model('billing.lastName')} />
```

once you start typing on the 2nd input field, the first one will disappear. it works on your example where you only had one property with 2 nested object `guest1` and `guest2`

**Comment by abraham-serafino** [comment] 2017-08-10 19:56
Thanks for catching this. It was caused by a mistaken belief on my part. Specifically, I thought setState merged new state with existing state recursively - but this is not the case.

I fixed this in the code for master using `lodash.merge` to recursively merge in the existing state. I will also update the tutorial steps to reflect this new info. shortly.

**Closed as completed** 2017-08-10 19:57 UTC
